### ISSUE TITLE
Error after closing the server - Change zombie plague to save ammo packs like pointshop

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#10]
After you close the server with the gamemode turned on, you can observe the LUA error in the console.

Console message;
[ERROR] gamemodes/zombieplague/gamemode/bankstorage/text.lua:14: attempt to concatenate a nil value
  1. Deposit - gamemodes/zombieplague/gamemode/bankstorage/text.lua:14
   2. Deposit - gamemodes/zombieplague/gamemode/sv_bank.lua:36
    3. v - gamemodes/zombieplague/gamemode/sv_bank.lua:78
     4. unknown - lua/includes/modules/hook.lua:84

**Comment by Nicholas-Fuchs** [comment]
Does this still happening?

**Comment by ErickMaksimets** [comment]
> Does this still happening?

yeah

**Comment by Nicholas-Fuchs** [comment]
Tried It sometimes and I didn't reproduce this error

**Comment by Nicholas-Fuchs** [comment]
Can't reproduce

**Comment by Nicholas-Fuchs** [comment]
This is still happening, but I can't reproduce

**Comment by Nicholas-Fuchs** [comment]
This is happening due the nill player entity that stays on the server after Garry's mod's server shutdown. I will need to change how zombie plague save player's ammo packs

**Comment by Nicholas-Fuchs** [comment]
Changed how server saves ammo packs. Now server will save current player's ammo pack and will use his SteamID64 to do that. This will occour every 5 seconds

**Comment by Nicholas-Fuchs** [comment]
Changed how ammo pack bank saves the ammo packs. It will save the player's ammo pack every 5 seconds using SteamID64 string reference.
