### ISSUE TITLE
FEATURE - Add M9K Weapons, and add M9K specialities as extra items

### ISSUE THREAD

**Issue by Nicholas-Fuchs** [Nicholas-Fuchs/zombieplague#102]

**Comment by Blueberryy** [comment]
add tfa cso2 guns

**Comment by ErickMaksimets** [comment]
Or maybe gamemode do not need extra content? I think if players want to add weapons, then they can do it without problems. I think weapon packs are personal question.

**Comment by Blueberryy** [comment]
ok boomer

**Comment by Nicholas-Fuchs** [comment]
Added M9K Specialities
