### ISSUE TITLE
SLAM's problem

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#109]
When you buy slam and throw 1-3 mines to the ground (without installing a laser), then when you buy again, money will be debited from you, but you will not get an additional 3 slam.
![ezgif-7-0ac8f0e64d3d](https://user-images.githubusercontent.com/59126348/73592467-7ba74680-4503-11ea-95b9-e620b636e38f.gif)

**Comment by Nicholas-Fuchs** [comment]
Changed how many SLAMs are given
