### ISSUE TITLE
 lua error in transport

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#118]
Honestly, I myself do not fully understand why this error appears.

When you try to fly on brush helicopters, the following error will appear:

[ERROR] gamemodes/zombieplague/gamemode/sv_eventmanager.lua:57: Tried to use a NULL entity!
  1. GetClass - [C]:-1
   2. unknown - gamemodes/zombieplague/gamemode/sv_eventmanager.lua:57

![ezgif-7-07797ce26874](https://user-images.githubusercontent.com/59126348/73744009-8d355c00-4758-11ea-8028-a3b14bfd2041.gif)

**Comment by Nicholas-Fuchs** [comment]
I guess this is happening due a miss handling of player damage.

Can you send the map name, so I will be able to test?

**Comment by ErickMaksimets** [comment]
the map with this helicopter has not yet come out)

**Comment by Nicholas-Fuchs** [comment]
This is happening due a unhandled damage (When player doesn't have a weapon), I tried to fix in: https://github.com/Nicholas-Fuchs/zombieplague/tree/ZP-118. I need you to test, as I don't have the map

**Comment by ErickMaksimets** [comment]
> This is happening due a unhandled damage (When player doesn't have a weapon), I tried to fix in: https://github.com/Nicholas-Fuchs/zombieplague/tree/ZP-118. I need you to test, as I don't have the map

Error still here

**Comment by Blueberryy** [comment]
Send map broskie

**Comment by ErickMaksimets** [comment]
> Send map broskie

Already in steam chat

**Comment by Nicholas-Fuchs** [comment]
Fixed using IsValid to Attacker:GetActiveWeapon() (As was returning a null weapon)
