### ISSUE TITLE
 the interface does not work correctly

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#120]
The interface in some languages ​​does not work correctly, in particular, crawls under a time table.
![image](https://user-images.githubusercontent.com/59126348/73987770-2081b380-494a-11ea-8dce-d7f8b4dcbc57.png)
![image](https://user-images.githubusercontent.com/59126348/73988061-3d1deb80-494a-11ea-8ee7-6bf2cf5c5303.png)

**Comment by Blueberryy** [comment]
Better move time tab a bit over of this line

**Comment by Nicholas-Fuchs** [comment]
ZP-115 is in developing. There you will be able to change HUD font and position

**Comment by Nicholas-Fuchs** [comment]
Has ZP-115 fix this issue in low resolution screen (As now you can change HUD positions). If you think this not solved the problem. Reopen this issue
