### ISSUE TITLE
Change zp_zombie_should_run to zp_zombie_should_walk

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#142]
We made a mistake when we tried to create zp_zombie_should_run
More precisely, this should work so that zombies have their default speed as RUNNING and not WALKING
Remove zombie running speed = kill all zombie classes

**Comment by Nicholas-Fuchs** [comment]
I think what we can do is change the zombie speed to the running speed instead changing this cvar. Changing this cvar will break totally the breath system
