### ISSUE TITLE
Small changes in ukrainian and russian translation

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#174]
Ukrainian 
NoticeInfect = "%s мізки були з'їдені %s...",
change to 
NoticeInfect = "Мізки %s були з'їдені %s...",

Russian
NoticeInfect = "%s мозги были съедены %s...",
change to
NoticeInfect = "Мозги %s были съедены %s...",

**Comment by Nicholas-Fuchs** [comment]
Fixed at ZP-174
