### ISSUE TITLE
Change walk speed for run speed suggested by Erick

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#179]
*facepalm*
We made a mistake creating this console command. According to my suggestions, zombies should always run, or with a choice between running and walking.

zp_zombie_should_walk 1 - zombies can run and walk
zp_zombie_shoud_walk 0 - zombies only can run

Default value - 0

By the way, bots also will be more strong with this change

**Comment by Nicholas-Fuchs** [comment]
Erick, as I told you, I set to default Zombies to run. Their walks speed is their run speed. If I made the constantly run, will break the breath system when it's enabled.

**Comment by Nicholas-Fuchs** [comment]
Updated at ZP-179
