### ISSUE TITLE
M9k support error

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#192]
When a zombie infects you, when you have a weapon in your hands from the m9k, this error will appear.

M9K Small Arms pack] lua/weapons/bobs_gun_base/shared.lua:664: attempt to call method 'KeyDown' (a nil value)
  1. unknown - lua/weapons/bobs_gun_base/shared.lua:664

Timer Failed! [Simple][@lua/weapons/bobs_gun_base/shared.lua (line 660)]

**Comment by Nicholas-Fuchs** [comment]
I guess this is not a problem with zombie plague. I think It's a problem with M9K weapons
