### ISSUE TITLE
Add 1.1 scale for tank and heavy class

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#197]
Make Entity:SetModelScale for tank and heavy
![image](https://user-images.githubusercontent.com/59126348/87256005-1420fa00-c498-11ea-991f-572209015131.png)

**Comment by Nicholas-Fuchs** [comment]
I was seeing that if I mess with player scale, their hitbox also are changed. I thing this can cause some troubles for the big boy. Like can fit in some place.
