### ISSUE TITLE
Additional ammo in the extra items store.

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#212]
Add the ability to purchase ammo for standard weapons. 30 bolts for a crossbow, 50 rounds for a shotgun, 300 rounds for everything else. +3 alternative ammo for smg

I think the price of 7 ammo packs will be fair.

**Comment by Nicholas-Fuchs** [comment]
https://github.com/Nicholas-Fuchs/zombieplague/tree/ZP-212 - Can you test it?
