### ISSUE TITLE
New balance for M9K weapons

### ISSUE THREAD

**Issue by Nicholas-Fuchs** [Nicholas-Fuchs/zombieplague#224]
M9K are very unbalanced. This should be changed

**Comment by ErickMaksimets** [comment]
### Assault Rifles
![Screenshot_1](https://user-images.githubusercontent.com/59126348/92993110-1c2d0280-f4f8-11ea-8d9e-0dee63f64036.jpg)

**Comment by ErickMaksimets** [comment]
### Pistols
![Screenshot_1](https://user-images.githubusercontent.com/59126348/93012973-28bf6280-f5ad-11ea-830e-242b048beee3.jpg)

**Comment by ErickMaksimets** [comment]
Submachine Guns
![image](https://user-images.githubusercontent.com/59126348/95676348-28bf7c00-0bc6-11eb-8741-cc8cc2f38912.png)
