### ISSUE TITLE
Tried to use a NULL entity (Scoreboard Error)

### ISSUE THREAD

**Issue by Bilwin** [Nicholas-Fuchs/zombieplague#274]
**ERROR**
```
[ERROR] gamemodes/zombieplague/gamemode/cl_scoreboard.lua:218: Tried to use a NULL entity!
  1. Text - [C]:-1
   2. UpdateFunction - gamemodes/zombieplague/gamemode/cl_scoreboard.lua:218
    3. unknown - gamemodes/zombieplague/gamemode/cl_scoreboard.lua:50

Timer Failed! [ScoreBoardUpdater][@gamemodes/zombieplague/gamemode/cl_scoreboard.lua (line 45)]
```

A player needs to disconnect from the server when somebody has enabled scoreboard

**Comment by Nicholas-Fuchs** [comment]
Oh, that's the way. Ok, I will give a try

**Comment by Nicholas-Fuchs** [comment]
TY Bilwin

**Comment by Nicholas-Fuchs** [comment]
can you give a try in this branch? https://github.com/Nicholas-Fuchs/zombieplague/tree/ZP-274

**Comment by ErickMaksimets** [comment]
We have new lua error

[X3omor|8|STEAM_0:1:447474984] Lua Error:

[ERROR] gamemodes/zombieplague/gamemode/cl_scoreboard.lua:192: Tried to use a NULL entity!
  1. IsMuted - [C]:-1
   2. UpdateFunction - gamemodes/zombieplague/gamemode/cl_scoreboard.lua:192
    3. unknown - gamemodes/zombieplague/gamemode/cl_scoreboard.lua:50



[ERROR] gamemodes/zombieplague/gamemode/cl_scoreboard.lua:192: Tried to use a NULL entity!
  1. IsMuted - [C]:-1
   2. UpdateFunction - gamemodes/zombieplague/gamemode/cl_scoreboard.lua:192
    3. unknown - gamemodes/zombieplague/gamemode/cl_scoreboard.lua:50

Timer Failed! [ScoreBoardUpdater][@gamemodes/zombieplague/gamemode/cl_scoreboard.lua (line 45)]
[Erick_Maksimets|5|STEAM_0:1:95980398] Lua Error:

[ERROR] gamemodes/zombieplague/gamemode/cl_scoreboard.lua:192: Tried to use a NULL entity!
  1. IsMuted - [C]:-1
   2. UpdateFunction - gamemodes/zombieplague/gamemode/cl_scoreboard.lua:192
    3. unknown - gamemodes/zombieplague/gamemode/cl_scoreboard.lua:50

**Comment by Nicholas-Fuchs** [comment]
merged, if this error still occours, i will cry
