### ISSUE TITLE
Dead Human's S.L.A.M

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#35]
If a human puts S.L.A.M before his death and a zombie explodes on it, then we may have received the LUA error.

1. Human puts S.L.A.M;
2. Human is dying;
3. Zombie jumps on S.L.A.M;
4. We see an LUA error in the console.

[ERROR] gamemodes/zombieplague/gamemode/sv_eventmanager.lua:54: Tried to use a NULL entity!
1. GetClass - [C]:-1
2. unknown - gamemodes/zombieplague/gamemode/sv_eventmanager.lua:54

**Comment by Nicholas-Fuchs** [comment]
Same error as https://github.com/Nicholas-Fuchs/zombieplague/issues/7
