### ISSUE TITLE
Camouflage class is broken

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#5]
When you select a camouflage class and enter zp_ability in the console, the game gives an error.
It works only when there is one player on the server, or when the zombie has not yet appeared.
This also works when you, as a zombie, killed the last human and type zp_ability in console before a new round begins.

Console message:
(for humans)
[ERROR] gamemodes/zombieplague/gamemode/classes/humans/camouflage.lua:12: attempt to index a nil value
  1. Ability - gamemodes/zombieplague/gamemode/classes/humans/camouflage.lua:12
   2. func - gamemodes/zombieplague/gamemode/sv_eventmanager.lua:371
    3. unknown - lua/includes/extensions/net.lua:32

(for zombies)
[ERROR] gamemodes/zombieplague/gamemode/classes/zombies/camouflage.lua:13: attempt to index a nil value
  1. Ability - gamemodes/zombieplague/gamemode/classes/zombies/camouflage.lua:13
   2. func - gamemodes/zombieplague/gamemode/sv_eventmanager.lua:371
    3. unknown - lua/includes/extensions/net.lua:32

**Comment by Nicholas-Fuchs** [comment]
Fixed at branch ZP-5
