### ISSUE TITLE
Make the interface more friendly

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#50]
This is not a bug, but still unpleasant.

In the interface, everything is written in white plain text which in some situations is not visible. For example, a game on cs_office, it is not possible to understand anything due to the solid color.

The solution to this problem can be to convert all letters to uppercase (change the font) and create a black panel for the letters.

Example:
![example](https://user-images.githubusercontent.com/59126348/71694398-beb4b380-2db7-11ea-897c-4ac04933d3bc.jpg)

**Comment by Nicholas-Fuchs** [comment]
Maybe it's better to make a VGUI to customize this options.

**Comment by Nicholas-Fuchs** [comment]
This was made with a HUD customizer.
