### ISSUE TITLE
sv_weaponmanager - Melee Error

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#54]
Before starting a new round, you must select the primary and secondary weapons in the weapon selection menu, leaving the menu open for melee weapons. After starting a new round, you will receive a LUA error.(again)

Console message:

[ERROR] gamemodes/zombieplague/gamemode/sv_weaponmanager.lua:134: bad argument #1 to 'Send' (Entity expected, got nil)
  1. Send - [C]:-1
   2. OpenMeleeWeaponMenu - gamemodes/zombieplague/gamemode/sv_weaponmanager.lua:134
    3. MakeHuman - gamemodes/zombieplague/gamemode/sv_player.lua:462
     4. Call - gamemodes/zombieplague/gamemode/sv_eventmanager.lua:295
      5. unknown - gamemodes/zombieplague/gamemode/sv_eventmanager.lua:187
       6. Spawn - [C]:-1
        7. Prepare - gamemodes/zombieplague/gamemode/sv_roundmanager.lua:100
         8. unknown - gamemodes/zombieplague/gamemode/sv_roundmanager.lua:109

**Comment by Nicholas-Fuchs** [comment]
This was caused because OpenMeleeWeaponMenu was called without ply.
