### ISSUE TITLE
Hands textures are not displayed in spectator mode

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#6]
When you enter the team of spectators, you can not see the texture of the hands. 

Usually it can be found in some incorrect place on the map.

It works for both zombies and humans. But in humans we see at least weapons.
![demo](https://user-images.githubusercontent.com/59126348/71327394-93f17200-2510-11ea-951a-1519f2534d01.png)

**Comment by Nicholas-Fuchs** [comment]
Fixed in the last update
