### ISSUE TITLE
Suggestion - Round intermission music

### ISSUE THREAD

**Issue by Blueberryy** [Nicholas-Fuchs/zombieplague#67]

**Comment by Nicholas-Fuchs** [comment]
What do you mean with "intermission"?

**Comment by Blueberryy** [comment]
Music that play when players spawns

**Comment by Blueberryy** [comment]
and this music end when game begun

**Comment by Nicholas-Fuchs** [comment]
Oh, like old zombie plague? I already tried to do that. But I don't know how to stop the music. One day I found on facepunch forum. But it has been shuted down
