### ISSUE TITLE
Dead Zombie's Grenade

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#7]
If a zombie throws a grenade at a man before his death, then after its explosion, a Lua error will appear in the console.

1. Zombie throws a grenade;
2. Human kills zombie;
3. A grenade explodes next to human;
4. We see an LUA error in the console.

[ERROR] gamemodes/zombieplague/gamemode/sv_eventmanager.lua:54: Tried to use a NULL entity!
  1. GetClass - [C]:-1
   2. unknown - gamemodes/zombieplague/gamemode/sv_eventmanager.lua:54

**Comment by Nicholas-Fuchs** [comment]
The reason why this is happening is because projectile weapons (RPG, Grenades, SLAM and crossbow) don't deal damage instantly. So when it calls for active weapon, a nil pointer is thrown

**Comment by Nicholas-Fuchs** [comment]
Issue fixed: Added an option to add projectileID to damage amplifier and ply:Alive() check
