### ISSUE TITLE
Zombie Bomber has no bombs.

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#8]
If we try to play as a Zombie Bomber class, we will not be able to see an infectious grenade that should be given out to this class for free.

This bug is probably caused by a recent update in Garry's mod that changes the default values ​​for grenade quantities.

I tried to copy part of the code from the extra items and managed to fix it.(Yeah, it's stupid, but it works)

![image](https://user-images.githubusercontent.com/59126348/71365591-25f88980-25a8-11ea-976d-bdc2b1a28632.png)

**Comment by Nicholas-Fuchs** [comment]
Zombie Plague was using Give instead GiveZombieAllowedWeapon function
