### ISSUE TITLE
Open Melee Weapon Menu Error

### ISSUE THREAD

**Issue by ErickMaksimets** [Nicholas-Fuchs/zombieplague#9]
Before starting a new round, you must select the primary and secondary weapons in the weapon selection menu, leaving the menu open for melee weapons. After starting a new round, you will receive a LUA error.

Console message:

[ERROR] gamemodes/zombieplague/gamemode/sv_player.lua:454: attempt to call method 'OpenMeleeWeaponMenu' (a nil value)
  1. MakeHuman - gamemodes/zombieplague/gamemode/sv_player.lua:454
   2. Call - gamemodes/zombieplague/gamemode/sv_eventmanager.lua:292
    3. unknown - gamemodes/zombieplague/gamemode/sv_eventmanager.lua:184
     4. Spawn - [C]:-1
      5. Prepare - gamemodes/zombieplague/gamemode/sv_roundmanager.lua:94
       6. unknown - gamemodes/zombieplague/gamemode/sv_roundmanager.lua:103

**Comment by Nicholas-Fuchs** [comment]
This error occours when you open and select a new primary weapon before a new round start. Probably I'm not checking if the weapon is null and I'm trying to give the weapon

**Comment by Nicholas-Fuchs** [comment]
This was caused due a mistake on WeaponManager name
